apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: codis.daas.dreamxos.com
spec:
  group: daas.dreamxos.com
  names:
    kind: Codis
    listKind: CodisList
    plural: codis
    singular: codis
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Codis is the Schema for the codis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CodisSpec defines the desired state of Codis
          type: object
        status:
          description: CodisStatus defines the observed state of Codis
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
